export { default as DashboardPage } from './DashboardPage';
export { default as ProductsPage } from './ProductsPage';
export { default as CouponsPage } from './CouponsPage';
export { default as CategoriesPage } from './CategoriesPage';
export { default as UsersPage } from './UsersPage';
export { default as AddProductPage } from './AddProductPage';
export { default as EditProductPage } from './EditProductPage';
export { default as AddCategoryPage } from './AddCategoryPage';
export { default as Inactive } from './Inactive';